name: POILoot
description: '${description}'
version: '${version}'

main: io.github.blackshadowhrd.poiloot.PoiLootPlugin
api-version: '26.2'
load: POSTWORLD

authors:
  - DocBoti
website: https://github.com/BlackShadowHRD/poiloot

permissions:
  poiloot.admin:
    description: Allows management and inspection of POILoot loot points
    default: op
