name: POILoot
description: '${description}'
version: '${version}'

main: io.github.blackshadowhrd.poiloot.PoiLootPlugin
api-version: '26.2'
load: POSTWORLD

authors:
  - DocBoti
website: https://github.com/BlackShadowHRD/poiloot

commands:
  poiloot:
    description: Manages POILoot loot points
    usage: /poiloot <version|inspect|register <loot-table-key>|deregister>
