name: GameLoot
description: '${description}'
version: '${version}'

main: io.github.blackshadowhrd.gameloot.GameLootPlugin
api-version: '26.2'
load: POSTWORLD

authors:
  - DocBoti
website: https://github.com/BlackShadowHRD/gameloot

permissions:
  gameloot.admin:
    description: Allows management and inspection of GameLoot loot points
    default: op
